<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schéma complet de départ (généré depuis le mapping Doctrine : tables, index, puis clés étrangères).
 *
 * Remplace l'historique des migrations précédentes, qui ne permettait pas de créer une base vierge.
 * - Base vierge : doctrine:migrations:migrate
 * - Base existante déjà à jour : doctrine:migrations:rollup (marque cette version comme exécutée)
 */
final class Version20261007195209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial complet de GETTESTED';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ability_estimate (id UUID NOT NULL, theta DOUBLE PRECISION NOT NULL, std_error DOUBLE PRECISION NOT NULL, estimated_level VARCHAR(50) NOT NULL, source VARCHAR(255) NOT NULL, skill_breakdown JSON DEFAULT NULL, estimated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, assessment_id UUID NOT NULL, level_id UUID NOT NULL, practice_session_id UUID DEFAULT NULL, enrollment_exam_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ability_estimated_at ON ability_estimate (estimated_at)');
        $this->addSql('CREATE INDEX IDX_CC977E8EA76ED395 ON ability_estimate (user_id)');
        $this->addSql('CREATE INDEX IDX_CC977E8EDD3DD5F1 ON ability_estimate (assessment_id)');
        $this->addSql('CREATE INDEX IDX_CC977E8E5FB14BA7 ON ability_estimate (level_id)');
        $this->addSql('CREATE INDEX IDX_CC977E8E4E20FDCF ON ability_estimate (practice_session_id)');
        $this->addSql('CREATE INDEX IDX_CC977E8E990235C4 ON ability_estimate (enrollment_exam_id)');
        $this->addSql('CREATE TABLE assessment (id UUID NOT NULL, label VARCHAR(255) NOT NULL, ref VARCHAR(50) NOT NULL, is_internal BOOLEAN NOT NULL, parent_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F7523D70727ACA70 ON assessment (parent_id)');
        $this->addSql('CREATE TABLE assessment_level (assessment_id UUID NOT NULL, level_id UUID NOT NULL, PRIMARY KEY (assessment_id, level_id))');
        $this->addSql('CREATE INDEX IDX_93CEF305DD3DD5F1 ON assessment_level (assessment_id)');
        $this->addSql('CREATE INDEX IDX_93CEF3055FB14BA7 ON assessment_level (level_id)');
        $this->addSql('CREATE TABLE assessment_skill (assessment_id UUID NOT NULL, skill_id UUID NOT NULL, PRIMARY KEY (assessment_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_5719DB61DD3DD5F1 ON assessment_skill (assessment_id)');
        $this->addSql('CREATE INDEX IDX_5719DB615585C142 ON assessment_skill (skill_id)');
        $this->addSql('CREATE TABLE assessment_ownership (id UUID NOT NULL, ownership_type VARCHAR(255) NOT NULL, relationship_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, institute_id UUID NOT NULL, assessment_id UUID NOT NULL, creator_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CAE11F78697B0F4C ON assessment_ownership (institute_id)');
        $this->addSql('CREATE INDEX IDX_CAE11F78DD3DD5F1 ON assessment_ownership (assessment_id)');
        $this->addSql('CREATE INDEX IDX_CAE11F7861220EA6 ON assessment_ownership (creator_id)');
        $this->addSql('CREATE TABLE blank_slot (id UUID NOT NULL, position INT NOT NULL, accepted_answers JSON NOT NULL, case_sensitive BOOLEAN NOT NULL, accent_sensitive BOOLEAN NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E3D01EE1E27F6BF ON blank_slot (question_id)');
        $this->addSql('CREATE TABLE candidate_response (id UUID NOT NULL, given_answer JSON NOT NULL, status VARCHAR(255) NOT NULL, score DOUBLE PRECISION NOT NULL, response_time_ms INT NOT NULL, answered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, theta_at_answer DOUBLE PRECISION DEFAULT NULL, information_value DOUBLE PRECISION DEFAULT NULL, question_id UUID NOT NULL, subject_question_id UUID DEFAULT NULL, enrollment_exam_id UUID DEFAULT NULL, practice_session_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_response_answered_at ON candidate_response (answered_at)');
        $this->addSql('CREATE INDEX IDX_9F2549281E27F6BF ON candidate_response (question_id)');
        $this->addSql('CREATE INDEX IDX_9F254928862E2E9B ON candidate_response (subject_question_id)');
        $this->addSql('CREATE INDEX IDX_9F254928990235C4 ON candidate_response (enrollment_exam_id)');
        $this->addSql('CREATE INDEX IDX_9F2549284E20FDCF ON candidate_response (practice_session_id)');
        $this->addSql('CREATE TABLE choice (id UUID NOT NULL, text TEXT NOT NULL, weight DOUBLE PRECISION NOT NULL, position INT NOT NULL, feedback TEXT DEFAULT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1AB5A921E27F6BF ON choice (question_id)');
        $this->addSql('CREATE TABLE country (code VARCHAR(2) NOT NULL, alpha3 VARCHAR(3) NOT NULL, name_original VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, name_fr VARCHAR(255) NOT NULL, flag VARCHAR(10) DEFAULT NULL, demonym_fr VARCHAR(100) DEFAULT NULL, demonym_en VARCHAR(100) DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C966C065E6E4 ON country (alpha3)');
        $this->addSql('CREATE TABLE country_language (country_code VARCHAR(2) NOT NULL, language_code VARCHAR(3) NOT NULL, PRIMARY KEY (country_code, language_code))');
        $this->addSql('CREATE INDEX IDX_E7112008F026BB7C ON country_language (country_code)');
        $this->addSql('CREATE INDEX IDX_E7112008451CDAD4 ON country_language (language_code)');
        $this->addSql('CREATE TABLE document_template (id UUID NOT NULL, label VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, is_default BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_type_id UUID NOT NULL, institute_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_18A1EEDA61232A4F ON document_template (document_type_id)');
        $this->addSql('CREATE INDEX IDX_18A1EEDA697B0F4C ON document_template (institute_id)');
        $this->addSql('CREATE TABLE document_type (id UUID NOT NULL, label VARCHAR(255) NOT NULL, code VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2B6ADBBA77153098 ON document_type (code)');
        $this->addSql('CREATE TABLE enrollment_exam (id UUID NOT NULL, final_score INT DEFAULT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enrollment_session_id UUID NOT NULL, scheduled_exam_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2DF66912F0462C97 ON enrollment_exam (enrollment_session_id)');
        $this->addSql('CREATE INDEX IDX_2DF66912334A08D5 ON enrollment_exam (scheduled_exam_id)');
        $this->addSql('CREATE TABLE enrollment_session (id UUID NOT NULL, reference_number VARCHAR(15) DEFAULT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) DEFAULT \'ACTIVE\' NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, information TEXT DEFAULT NULL, user_id UUID NOT NULL, session_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1ECBBE818BF1AE50 ON enrollment_session (reference_number)');
        $this->addSql('CREATE INDEX IDX_1ECBBE81A76ED395 ON enrollment_session (user_id)');
        $this->addSql('CREATE INDEX IDX_1ECBBE81613FECDF ON enrollment_session (session_id)');
        $this->addSql('CREATE TABLE exam (id UUID NOT NULL, label VARCHAR(255) NOT NULL, is_written BOOLEAN NOT NULL, is_option BOOLEAN NOT NULL, coeff INT DEFAULT NULL, nbr_questions INT DEFAULT NULL, duration INT DEFAULT NULL, success_score INT DEFAULT NULL, price_amount DOUBLE PRECISION DEFAULT NULL, price_currency VARCHAR(3) DEFAULT NULL, price_tva DOUBLE PRECISION DEFAULT NULL, assessment_id UUID NOT NULL, level_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38BBA6C6DD3DD5F1 ON exam (assessment_id)');
        $this->addSql('CREATE INDEX IDX_38BBA6C65FB14BA7 ON exam (level_id)');
        $this->addSql('CREATE TABLE exam_skill (exam_id UUID NOT NULL, skill_id UUID NOT NULL, PRIMARY KEY (exam_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_CD8E2C7578D5E91 ON exam_skill (exam_id)');
        $this->addSql('CREATE INDEX IDX_CD8E2C75585C142 ON exam_skill (skill_id)');
        $this->addSql('CREATE TABLE exam_center (id UUID NOT NULL, label VARCHAR(255) NOT NULL, is_default BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address_address1 VARCHAR(255) DEFAULT NULL, address_address2 VARCHAR(255) DEFAULT NULL, address_zipcode VARCHAR(20) DEFAULT NULL, address_city VARCHAR(255) DEFAULT NULL, address_country_code VARCHAR(2) DEFAULT NULL, institute_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8BC3BDAE697B0F4C ON exam_center (institute_id)');
        $this->addSql('CREATE TABLE fill_blank_question (blank_symbol VARCHAR(10) NOT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE question (id UUID NOT NULL, label VARCHAR(255) NOT NULL, text TEXT NOT NULL, instruction TEXT DEFAULT NULL, duration INT DEFAULT NULL, max_points DOUBLE PRECISION NOT NULL, status VARCHAR(255) NOT NULL, irt_difficulty DOUBLE PRECISION DEFAULT NULL, irt_discrimination DOUBLE PRECISION DEFAULT NULL, irt_guessing DOUBLE PRECISION DEFAULT NULL, irt_std_error DOUBLE PRECISION DEFAULT NULL, times_administered INT NOT NULL, success_rate DOUBLE PRECISION DEFAULT NULL, avg_response_time_ms INT DEFAULT NULL, is_seed_item BOOLEAN NOT NULL, retired_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, retired_reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, assessment_id UUID NOT NULL, level_id UUID NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6F7494EDD3DD5F1 ON question (assessment_id)');
        $this->addSql('CREATE INDEX IDX_B6F7494E5FB14BA7 ON question (level_id)');
        $this->addSql('CREATE TABLE question_skill (question_id UUID NOT NULL, skill_id UUID NOT NULL, PRIMARY KEY (question_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_6ED6F5731E27F6BF ON question_skill (question_id)');
        $this->addSql('CREATE INDEX IDX_6ED6F5735585C142 ON question_skill (skill_id)');
        $this->addSql('CREATE TABLE highlight_question (id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE highlight_zone (id UUID NOT NULL, start_index INT NOT NULL, end_index INT NOT NULL, is_correct BOOLEAN NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3B7BA631E27F6BF ON highlight_zone (question_id)');
        $this->addSql('CREATE TABLE institute (id UUID NOT NULL, label VARCHAR(255) NOT NULL, status VARCHAR(20) DEFAULT \'ACTIVE\' NOT NULL, email VARCHAR(180) DEFAULT NULL, siteweb VARCHAR(255) DEFAULT NULL, social_networks JSON DEFAULT NULL, vat_number VARCHAR(50) DEFAULT NULL, siren VARCHAR(9) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, legal_form VARCHAR(50) DEFAULT NULL, share_capital VARCHAR(50) DEFAULT NULL, rcs_city VARCHAR(100) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, cover_position_y INT DEFAULT NULL, address_address1 VARCHAR(255) DEFAULT NULL, address_address2 VARCHAR(255) DEFAULT NULL, address_zipcode VARCHAR(20) DEFAULT NULL, address_city VARCHAR(255) DEFAULT NULL, address_country_code VARCHAR(2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE institute_exam_pricing (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, price_amount DOUBLE PRECISION DEFAULT NULL, price_currency VARCHAR(3) DEFAULT NULL, price_tva DOUBLE PRECISION DEFAULT NULL, institute_id UUID NOT NULL, exam_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_91D5446E697B0F4C ON institute_exam_pricing (institute_id)');
        $this->addSql('CREATE INDEX IDX_91D5446E578D5E91 ON institute_exam_pricing (exam_id)');
        $this->addSql('CREATE TABLE institute_membership (id UUID NOT NULL, role VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT \'ACTIVE\' NOT NULL, since TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, institute_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX unique_user_institute ON institute_membership (user_id, institute_id)');
        $this->addSql('CREATE INDEX IDX_5197D5FDA76ED395 ON institute_membership (user_id)');
        $this->addSql('CREATE INDEX IDX_5197D5FD697B0F4C ON institute_membership (institute_id)');
        $this->addSql('CREATE TABLE invoice (id UUID NOT NULL, invoice_number VARCHAR(50) DEFAULT NULL, invoice_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, service_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, invoice_type VARCHAR(255) NOT NULL, business_type VARCHAR(255) NOT NULL, operation_category VARCHAR(255) NOT NULL, payment_due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, payment_terms VARCHAR(255) DEFAULT NULL, early_payment_discount VARCHAR(255) DEFAULT NULL, late_payment_penalty_rate DOUBLE PRECISION DEFAULT NULL, fixed_recovery_indemnity DOUBLE PRECISION DEFAULT NULL, total_ht DOUBLE PRECISION NOT NULL, total_tva DOUBLE PRECISION NOT NULL, total_ttc DOUBLE PRECISION NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(255) NOT NULL, pdf_path VARCHAR(255) DEFAULT NULL, seller_name VARCHAR(255) NOT NULL, seller_address VARCHAR(255) DEFAULT NULL, seller_city VARCHAR(100) DEFAULT NULL, seller_zipcode VARCHAR(20) DEFAULT NULL, seller_country_code VARCHAR(5) DEFAULT NULL, seller_vat_number VARCHAR(50) DEFAULT NULL, seller_siren VARCHAR(9) DEFAULT NULL, seller_siret VARCHAR(14) DEFAULT NULL, seller_legal_form VARCHAR(50) DEFAULT NULL, seller_share_capital VARCHAR(50) DEFAULT NULL, seller_rcs_city VARCHAR(100) DEFAULT NULL, seller_logo_url VARCHAR(255) DEFAULT NULL, buyer_name VARCHAR(255) NOT NULL, buyer_address VARCHAR(255) DEFAULT NULL, buyer_city VARCHAR(100) DEFAULT NULL, buyer_zipcode VARCHAR(20) DEFAULT NULL, buyer_country_code VARCHAR(5) DEFAULT NULL, buyer_vat_number VARCHAR(50) DEFAULT NULL, buyer_siren VARCHAR(9) DEFAULT NULL, buyer_siret VARCHAR(14) DEFAULT NULL, buyer_legal_form VARCHAR(50) DEFAULT NULL, buyer_share_capital VARCHAR(50) DEFAULT NULL, buyer_rcs_city VARCHAR(100) DEFAULT NULL, buyer_logo_url VARCHAR(255) DEFAULT NULL, credited_invoice_id UUID DEFAULT NULL, enrollment_session_id UUID DEFAULT NULL, assessment_ownership_id UUID DEFAULT NULL, institute_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_906517442DA68207 ON invoice (invoice_number)');
        $this->addSql('CREATE INDEX IDX_906517446A17B032 ON invoice (credited_invoice_id)');
        $this->addSql('CREATE INDEX IDX_90651744F0462C97 ON invoice (enrollment_session_id)');
        $this->addSql('CREATE INDEX IDX_9065174426F42062 ON invoice (assessment_ownership_id)');
        $this->addSql('CREATE INDEX IDX_90651744697B0F4C ON invoice (institute_id)');
        $this->addSql('CREATE TABLE invoice_line (id UUID NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, quantity INT NOT NULL, unit_price_ht DOUBLE PRECISION NOT NULL, tva_rate DOUBLE PRECISION NOT NULL, tva_amount DOUBLE PRECISION NOT NULL, total_ht DOUBLE PRECISION NOT NULL, total_ttc DOUBLE PRECISION NOT NULL, invoice_id UUID NOT NULL, exam_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3D1D6932989F1FD ON invoice_line (invoice_id)');
        $this->addSql('CREATE INDEX IDX_D3D1D693578D5E91 ON invoice_line (exam_id)');
        $this->addSql('CREATE TABLE language (code VARCHAR(3) NOT NULL, name_original VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, name_fr VARCHAR(255) NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE level (id UUID NOT NULL, label VARCHAR(255) NOT NULL, ref VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE matching_pair (id UUID NOT NULL, left_text TEXT NOT NULL, right_text TEXT NOT NULL, position INT NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F54D4BDE1E27F6BF ON matching_pair (question_id)');
        $this->addSql('CREATE TABLE matching_question (shuffle_on_display BOOLEAN NOT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE mcq_question (is_multiple_answer BOOLEAN NOT NULL, shuffle_choices BOOLEAN NOT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE media (id UUID NOT NULL, type VARCHAR(255) NOT NULL, url VARCHAR(500) NOT NULL, description VARCHAR(255) DEFAULT NULL, position INT NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10C1E27F6BF ON media (question_id)');
        $this->addSql('CREATE TABLE ordering_item (id UUID NOT NULL, text TEXT NOT NULL, correct_position INT NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_62D0868D1E27F6BF ON ordering_item (question_id)');
        $this->addSql('CREATE TABLE ordering_question (shuffle_on_display BOOLEAN NOT NULL, id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE payment (id UUID NOT NULL, amount DOUBLE PRECISION NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payment_method VARCHAR(255) NOT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, refunded_payment_id UUID DEFAULT NULL, invoice_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840DAA16C8A7 ON payment (refunded_payment_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D2989F1FD ON payment (invoice_id)');
        $this->addSql('CREATE TABLE practice_session (id UUID NOT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_questions INT NOT NULL, questions_answered INT NOT NULL, initial_theta DOUBLE PRECISION NOT NULL, final_theta DOUBLE PRECISION DEFAULT NULL, final_std_error DOUBLE PRECISION DEFAULT NULL, estimated_level VARCHAR(50) DEFAULT NULL, skill_scores JSON DEFAULT NULL, max_questions INT NOT NULL, stopping_se_threshold DOUBLE PRECISION NOT NULL, user_id UUID NOT NULL, assessment_id UUID NOT NULL, level_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DE33C9D0A76ED395 ON practice_session (user_id)');
        $this->addSql('CREATE INDEX IDX_DE33C9D0DD3DD5F1 ON practice_session (assessment_id)');
        $this->addSql('CREATE INDEX IDX_DE33C9D05FB14BA7 ON practice_session (level_id)');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE scheduled_exam (id UUID NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room VARCHAR(255) DEFAULT NULL, address_address1 VARCHAR(255) DEFAULT NULL, address_address2 VARCHAR(255) DEFAULT NULL, address_zipcode VARCHAR(20) DEFAULT NULL, address_city VARCHAR(255) DEFAULT NULL, address_country_code VARCHAR(2) DEFAULT NULL, exam_center_id UUID DEFAULT NULL, exam_id UUID NOT NULL, session_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F77AE1EFE6A1F62E ON scheduled_exam (exam_center_id)');
        $this->addSql('CREATE INDEX IDX_F77AE1EF578D5E91 ON scheduled_exam (exam_id)');
        $this->addSql('CREATE INDEX IDX_F77AE1EF613FECDF ON scheduled_exam (session_id)');
        $this->addSql('CREATE TABLE scheduled_exam_examinator (scheduled_exam_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (scheduled_exam_id, user_id))');
        $this->addSql('CREATE INDEX IDX_736F7EED334A08D5 ON scheduled_exam_examinator (scheduled_exam_id)');
        $this->addSql('CREATE INDEX IDX_736F7EEDA76ED395 ON scheduled_exam_examinator (user_id)');
        $this->addSql('CREATE TABLE "session" (id UUID NOT NULL, "start" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, limit_date_subscribe TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, places_available INT DEFAULT NULL, status VARCHAR(255) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked_automatically_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, assessment_id UUID NOT NULL, level_id UUID DEFAULT NULL, institute_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D044D5D4DD3DD5F1 ON "session" (assessment_id)');
        $this->addSql('CREATE INDEX IDX_D044D5D45FB14BA7 ON "session" (level_id)');
        $this->addSql('CREATE INDEX IDX_D044D5D4697B0F4C ON "session" (institute_id)');
        $this->addSql('CREATE TABLE session_document_publication (id UUID NOT NULL, is_auto_published BOOLEAN NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id UUID NOT NULL, document_type_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX unique_session_doctype ON session_document_publication (session_id, document_type_id)');
        $this->addSql('CREATE INDEX IDX_47BA810613FECDF ON session_document_publication (session_id)');
        $this->addSql('CREATE INDEX IDX_47BA81061232A4F ON session_document_publication (document_type_id)');
        $this->addSql('CREATE TABLE skill (id UUID NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, parent_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E3DE477727ACA70 ON skill (parent_id)');
        $this->addSql('CREATE TABLE stripe_account (id UUID NOT NULL, stripe_id VARCHAR(255) NOT NULL, is_activated BOOLEAN NOT NULL, charges_enabled BOOLEAN NOT NULL, payouts_enabled BOOLEAN NOT NULL, onboarding_complete BOOLEAN NOT NULL, commission_percent NUMERIC(5, 2) DEFAULT NULL, institute_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52F1675E697B0F4C ON stripe_account (institute_id)');
        $this->addSql('CREATE TABLE subject (id UUID NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, mode VARCHAR(20) NOT NULL, passing_score DOUBLE PRECISION DEFAULT NULL, total_max_points DOUBLE PRECISION DEFAULT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scheduled_exam_id UUID NOT NULL, locked_by_id UUID DEFAULT NULL, composition_rule_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX unique_subject_scheduled_exam ON subject (scheduled_exam_id)');
        $this->addSql('CREATE INDEX IDX_FBCE3E7A7A88E00 ON subject (locked_by_id)');
        $this->addSql('CREATE INDEX IDX_FBCE3E7A69391429 ON subject (composition_rule_id)');
        $this->addSql('CREATE TABLE subject_composition_rule (id UUID NOT NULL, total_questions INT NOT NULL, total_seed_questions INT NOT NULL, duration_minutes INT NOT NULL, skill_distribution JSON DEFAULT NULL, difficulty_distribution JSON DEFAULT NULL, min_spacing_days_global INT NOT NULL, min_spacing_days_same_institute INT NOT NULL, max_exposure_rate DOUBLE PRECISION NOT NULL, assessment_id UUID NOT NULL, level_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA7FEC13DD3DD5F1 ON subject_composition_rule (assessment_id)');
        $this->addSql('CREATE INDEX IDX_EA7FEC135FB14BA7 ON subject_composition_rule (level_id)');
        $this->addSql('CREATE TABLE subject_question (id UUID NOT NULL, position INT NOT NULL, is_seed BOOLEAN NOT NULL, points_override DOUBLE PRECISION DEFAULT NULL, subject_id UUID NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX unique_subject_question ON subject_question (subject_id, question_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_subject_position ON subject_question (subject_id, position)');
        $this->addSql('CREATE INDEX IDX_8E8A092623EDC87 ON subject_question (subject_id)');
        $this->addSql('CREATE INDEX IDX_8E8A09261E27F6BF ON subject_question (question_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, avatar VARCHAR(255) DEFAULT NULL, civility VARCHAR(255) NOT NULL, gender VARCHAR(255) DEFAULT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, phone_country_code VARCHAR(5) DEFAULT NULL, phone_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone_verification_code VARCHAR(255) DEFAULT NULL, phone_verification_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, birthday DATE DEFAULT NULL, is_verified BOOLEAN NOT NULL, email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, candidate_number VARCHAR(10) DEFAULT NULL, previous_registration_number VARCHAR(50) DEFAULT NULL, platform_role VARCHAR(255) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, address_address1 VARCHAR(255) DEFAULT NULL, address_address2 VARCHAR(255) DEFAULT NULL, address_zipcode VARCHAR(20) DEFAULT NULL, address_city VARCHAR(255) DEFAULT NULL, address_country_code VARCHAR(2) DEFAULT NULL, native_country_code VARCHAR(2) DEFAULT NULL, nationality_code VARCHAR(2) DEFAULT NULL, firstlanguage_code VARCHAR(3) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64922A34188 ON "user" (candidate_number)');
        $this->addSql('CREATE INDEX idx_user_deleted_at ON "user" (deleted_at)');
        $this->addSql('CREATE INDEX IDX_8D93D649573721DC ON "user" (native_country_code)');
        $this->addSql('CREATE INDEX IDX_8D93D649BFB2B51C ON "user" (nationality_code)');
        $this->addSql('CREATE INDEX IDX_8D93D6496AB3EEEC ON "user" (firstlanguage_code)');
        $this->addSql('ALTER TABLE ability_estimate ADD CONSTRAINT FK_CC977E8EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ability_estimate ADD CONSTRAINT FK_CC977E8EDD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ability_estimate ADD CONSTRAINT FK_CC977E8E5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ability_estimate ADD CONSTRAINT FK_CC977E8E4E20FDCF FOREIGN KEY (practice_session_id) REFERENCES practice_session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ability_estimate ADD CONSTRAINT FK_CC977E8E990235C4 FOREIGN KEY (enrollment_exam_id) REFERENCES enrollment_exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment ADD CONSTRAINT FK_F7523D70727ACA70 FOREIGN KEY (parent_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_level ADD CONSTRAINT FK_93CEF305DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assessment_level ADD CONSTRAINT FK_93CEF3055FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assessment_skill ADD CONSTRAINT FK_5719DB61DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assessment_skill ADD CONSTRAINT FK_5719DB615585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assessment_ownership ADD CONSTRAINT FK_CAE11F78697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_ownership ADD CONSTRAINT FK_CAE11F78DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_ownership ADD CONSTRAINT FK_CAE11F7861220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE blank_slot ADD CONSTRAINT FK_1E3D01EE1E27F6BF FOREIGN KEY (question_id) REFERENCES fill_blank_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_response ADD CONSTRAINT FK_9F2549281E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_response ADD CONSTRAINT FK_9F254928862E2E9B FOREIGN KEY (subject_question_id) REFERENCES subject_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_response ADD CONSTRAINT FK_9F254928990235C4 FOREIGN KEY (enrollment_exam_id) REFERENCES enrollment_exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_response ADD CONSTRAINT FK_9F2549284E20FDCF FOREIGN KEY (practice_session_id) REFERENCES practice_session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A921E27F6BF FOREIGN KEY (question_id) REFERENCES mcq_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE country_language ADD CONSTRAINT FK_E7112008F026BB7C FOREIGN KEY (country_code) REFERENCES country (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE country_language ADD CONSTRAINT FK_E7112008451CDAD4 FOREIGN KEY (language_code) REFERENCES language (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_template ADD CONSTRAINT FK_18A1EEDA61232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_template ADD CONSTRAINT FK_18A1EEDA697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollment_exam ADD CONSTRAINT FK_2DF66912F0462C97 FOREIGN KEY (enrollment_session_id) REFERENCES enrollment_session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollment_exam ADD CONSTRAINT FK_2DF66912334A08D5 FOREIGN KEY (scheduled_exam_id) REFERENCES scheduled_exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollment_session ADD CONSTRAINT FK_1ECBBE81A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enrollment_session ADD CONSTRAINT FK_1ECBBE81613FECDF FOREIGN KEY (session_id) REFERENCES "session" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C6DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C65FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_skill ADD CONSTRAINT FK_CD8E2C7578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_skill ADD CONSTRAINT FK_CD8E2C75585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_center ADD CONSTRAINT FK_8BC3BDAE697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fill_blank_question ADD CONSTRAINT FK_8E899C3DBF396750 FOREIGN KEY (id) REFERENCES question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494EDD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question_skill ADD CONSTRAINT FK_6ED6F5731E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE question_skill ADD CONSTRAINT FK_6ED6F5735585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE highlight_question ADD CONSTRAINT FK_D4D2877EBF396750 FOREIGN KEY (id) REFERENCES question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE highlight_zone ADD CONSTRAINT FK_A3B7BA631E27F6BF FOREIGN KEY (question_id) REFERENCES highlight_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE institute_exam_pricing ADD CONSTRAINT FK_91D5446E697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE institute_exam_pricing ADD CONSTRAINT FK_91D5446E578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE institute_membership ADD CONSTRAINT FK_5197D5FDA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE institute_membership ADD CONSTRAINT FK_5197D5FD697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517446A17B032 FOREIGN KEY (credited_invoice_id) REFERENCES invoice (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744F0462C97 FOREIGN KEY (enrollment_session_id) REFERENCES enrollment_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174426F42062 FOREIGN KEY (assessment_ownership_id) REFERENCES assessment_ownership (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D6932989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D693578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matching_pair ADD CONSTRAINT FK_F54D4BDE1E27F6BF FOREIGN KEY (question_id) REFERENCES matching_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matching_question ADD CONSTRAINT FK_EDADE997BF396750 FOREIGN KEY (id) REFERENCES question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mcq_question ADD CONSTRAINT FK_63ABAD96BF396750 FOREIGN KEY (id) REFERENCES question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C1E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ordering_item ADD CONSTRAINT FK_62D0868D1E27F6BF FOREIGN KEY (question_id) REFERENCES ordering_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ordering_question ADD CONSTRAINT FK_C486E739BF396750 FOREIGN KEY (id) REFERENCES question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DAA16C8A7 FOREIGN KEY (refunded_payment_id) REFERENCES payment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE practice_session ADD CONSTRAINT FK_DE33C9D0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE practice_session ADD CONSTRAINT FK_DE33C9D0DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE practice_session ADD CONSTRAINT FK_DE33C9D05FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduled_exam ADD CONSTRAINT FK_F77AE1EFE6A1F62E FOREIGN KEY (exam_center_id) REFERENCES exam_center (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduled_exam ADD CONSTRAINT FK_F77AE1EF578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduled_exam ADD CONSTRAINT FK_F77AE1EF613FECDF FOREIGN KEY (session_id) REFERENCES "session" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scheduled_exam_examinator ADD CONSTRAINT FK_736F7EED334A08D5 FOREIGN KEY (scheduled_exam_id) REFERENCES scheduled_exam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scheduled_exam_examinator ADD CONSTRAINT FK_736F7EEDA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE "session" ADD CONSTRAINT FK_D044D5D4DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "session" ADD CONSTRAINT FK_D044D5D45FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "session" ADD CONSTRAINT FK_D044D5D4697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_document_publication ADD CONSTRAINT FK_47BA810613FECDF FOREIGN KEY (session_id) REFERENCES "session" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_document_publication ADD CONSTRAINT FK_47BA81061232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477727ACA70 FOREIGN KEY (parent_id) REFERENCES skill (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stripe_account ADD CONSTRAINT FK_52F1675E697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7A334A08D5 FOREIGN KEY (scheduled_exam_id) REFERENCES scheduled_exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7A7A88E00 FOREIGN KEY (locked_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7A69391429 FOREIGN KEY (composition_rule_id) REFERENCES subject_composition_rule (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject_composition_rule ADD CONSTRAINT FK_EA7FEC13DD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject_composition_rule ADD CONSTRAINT FK_EA7FEC135FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject_question ADD CONSTRAINT FK_8E8A092623EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject_question ADD CONSTRAINT FK_8E8A09261E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649573721DC FOREIGN KEY (native_country_code) REFERENCES country (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649BFB2B51C FOREIGN KEY (nationality_code) REFERENCES country (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6496AB3EEEC FOREIGN KEY (firstlanguage_code) REFERENCES language (code) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS "user" CASCADE');
        $this->addSql('DROP TABLE IF EXISTS subject_question CASCADE');
        $this->addSql('DROP TABLE IF EXISTS subject_composition_rule CASCADE');
        $this->addSql('DROP TABLE IF EXISTS subject CASCADE');
        $this->addSql('DROP TABLE IF EXISTS stripe_account CASCADE');
        $this->addSql('DROP TABLE IF EXISTS skill CASCADE');
        $this->addSql('DROP TABLE IF EXISTS session_document_publication CASCADE');
        $this->addSql('DROP TABLE IF EXISTS "session" CASCADE');
        $this->addSql('DROP TABLE IF EXISTS scheduled_exam_examinator CASCADE');
        $this->addSql('DROP TABLE IF EXISTS scheduled_exam CASCADE');
        $this->addSql('DROP TABLE IF EXISTS refresh_tokens CASCADE');
        $this->addSql('DROP TABLE IF EXISTS practice_session CASCADE');
        $this->addSql('DROP TABLE IF EXISTS payment CASCADE');
        $this->addSql('DROP TABLE IF EXISTS ordering_question CASCADE');
        $this->addSql('DROP TABLE IF EXISTS ordering_item CASCADE');
        $this->addSql('DROP TABLE IF EXISTS media CASCADE');
        $this->addSql('DROP TABLE IF EXISTS mcq_question CASCADE');
        $this->addSql('DROP TABLE IF EXISTS matching_question CASCADE');
        $this->addSql('DROP TABLE IF EXISTS matching_pair CASCADE');
        $this->addSql('DROP TABLE IF EXISTS level CASCADE');
        $this->addSql('DROP TABLE IF EXISTS language CASCADE');
        $this->addSql('DROP TABLE IF EXISTS invoice_line CASCADE');
        $this->addSql('DROP TABLE IF EXISTS invoice CASCADE');
        $this->addSql('DROP TABLE IF EXISTS institute_membership CASCADE');
        $this->addSql('DROP TABLE IF EXISTS institute_exam_pricing CASCADE');
        $this->addSql('DROP TABLE IF EXISTS institute CASCADE');
        $this->addSql('DROP TABLE IF EXISTS highlight_zone CASCADE');
        $this->addSql('DROP TABLE IF EXISTS highlight_question CASCADE');
        $this->addSql('DROP TABLE IF EXISTS question_skill CASCADE');
        $this->addSql('DROP TABLE IF EXISTS question CASCADE');
        $this->addSql('DROP TABLE IF EXISTS fill_blank_question CASCADE');
        $this->addSql('DROP TABLE IF EXISTS exam_center CASCADE');
        $this->addSql('DROP TABLE IF EXISTS exam_skill CASCADE');
        $this->addSql('DROP TABLE IF EXISTS exam CASCADE');
        $this->addSql('DROP TABLE IF EXISTS enrollment_session CASCADE');
        $this->addSql('DROP TABLE IF EXISTS enrollment_exam CASCADE');
        $this->addSql('DROP TABLE IF EXISTS document_type CASCADE');
        $this->addSql('DROP TABLE IF EXISTS document_template CASCADE');
        $this->addSql('DROP TABLE IF EXISTS country_language CASCADE');
        $this->addSql('DROP TABLE IF EXISTS country CASCADE');
        $this->addSql('DROP TABLE IF EXISTS choice CASCADE');
        $this->addSql('DROP TABLE IF EXISTS candidate_response CASCADE');
        $this->addSql('DROP TABLE IF EXISTS blank_slot CASCADE');
        $this->addSql('DROP TABLE IF EXISTS assessment_ownership CASCADE');
        $this->addSql('DROP TABLE IF EXISTS assessment_skill CASCADE');
        $this->addSql('DROP TABLE IF EXISTS assessment_level CASCADE');
        $this->addSql('DROP TABLE IF EXISTS assessment CASCADE');
        $this->addSql('DROP TABLE IF EXISTS ability_estimate CASCADE');
    }
}
